version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      nitro:
        patterns:
          - "nitrogen"
          - "react-native-nitro-modules"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "h3-js"
      - dependency-name: "react"
      - dependency-name: "react-native"
      - dependency-name: "@react-native/*"
      - dependency-name: "@react-native-community/*"
      - dependency-name: "metro"
      - dependency-name: "metro-*"
      - dependency-name: "hermes-compiler"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
